# Generated by Django 4.2.29 on 2026-03-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(max_length=64)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "slug"], name="products_store_i_977d48_idx"
                    ),
                    models.Index(
                        fields=["store", "sku"], name="products_store_i_83486f_idx"
                    ),
                    models.Index(
                        fields=["store", "is_active"],
                        name="products_store_i_7e53ff_idx",
                    ),
                ],
                "unique_together": {("store", "sku"), ("store", "slug")},
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["store", "slug"], name="categories_store_i_cc7a4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("store", "slug")},
        ),
    ]
